#!/bin/bash
#script for ip rotation without authentication

systemctl stop firewalld 2>/dev/null
rm  /usr/local/etc/3proxy/bin/3proxy 2>/dev/null
rm -rf /home/proxy-installer 2>/dev/null
rm -rf /usr/local/etc/3proxy/3proxy.cfg

echo "Enter ipv6 network address for eg: 2600:3c00:f03c:4dfd"
read IP6

IP4=$(curl -4 -s icanhazip.com)

echo "Internal ip = ${IP4}. Exteranl sub for ip6 = ${IP6}"

echo "Starting Port"
read start_port
echo "Ending Port"
read end_port
FIRST_PORT=$start_port
LAST_PORT=$end_port
echo "IP rotation time (for eg: 10, 5, 60) in seconds"
read timer


yum -y install gcc net-tools make tar zip 2>/dev/null
echo "installing apps"


install_3proxy() {
    echo "installing 3proxy"
    curl -Lb  /tmp/gcokie "https://drive.google.com/uc?export=download&confirm=Uq6r&id=1xZj_U-JlC5oSIRJOmJemvz0JV3eQG03m" -o "SomeBigFile.tar.gz" && tar -xzvf SomeBigFile.tar.gz && rm SomeBigFile.tar.gz

    cd 3proxy-3proxy-0.8.6
   echo "compiling proxy server..."
    make -f Makefile.Linux
    mkdir -p /usr/local/etc/3proxy/{bin,logs,stat}
    cp src/3proxy /usr/local/etc/3proxy/bin/
    cp ./scripts/rc.d/proxy.sh /etc/init.d/3proxy
    chmod +x /etc/init.d/3proxy

    chkconfig 3proxy on

    cd $WORKDIR
    echo "initialising proxy server.."
}
echo "working folder = /home/proxy-installer"

echo ""
WORKDIR="/home/proxy-installer"
WORKDATA="${WORKDIR}/data.txt"
mkdir $WORKDIR && cd $_

install_3proxy


random() {
        tr </dev/urandom -dc A-Za-z0-9 | head -c5
        echo
}

array=(1 2 3 4 5 6 7 8 9 0 a b c d e f)
gen64() {
        ip64() {
                echo "${array[$RANDOM % 16]}${array[$RANDOM % 16]}${array[$RANDOM % 16]}${array[$RANDOM % 16]}"
        }
        echo "$1:$(ip64):$(ip64):$(ip64):$(ip64)"
}
gen_3proxy() {
    cat <<EOF
daemon
maxconn 4000
nscache 65536
timeouts 1 5 30 60 180 1800 15 60
setgid 65535
setuid 65535
flush

$(awk -F "/" '{print "proxy -6 -n -a -p" $2 " -i" $1 " -e"$3"\n" \
"flush\n"}' ${WORKDATA})
EOF
}

gen_proxy_file_for_user() {
    cat >proxy.txt <<EOF
$(awk -F "/" '{print $1 ":" $2  }' ${WORKDATA})
EOF
}

upload_proxy() {
    local PASS=$(random)
    zip --password $PASS proxy.zip proxy.txt
    URL=$(curl -s --upload-file proxy.zip https://transfer.sh/proxy.zip)

    echo "Proxy is ready! Format IP:PORT"
    echo "Download zip archive from: ${URL}"
    echo "Password: ${PASS}"

}
gen_data() {
    seq $FIRST_PORT $LAST_PORT | while read port; do
        echo "$IP4/$port/$(gen64 $IP6)"
    done
}

gen_iptables() {
    cat <<EOF
    $(awk -F "/" '{print "iptables -I INPUT -p tcp --dport " $2 "  -m state --state NEW -j ACCEPT"}' ${WORKDATA})
EOF
}
gen_ifconfig() {
    cat <<EOF
$(awk -F "/" '{print "ifconfig eth0 inet6 add " $3 "/64"}' ${WORKDATA})
EOF
}

while true; 
do  

gen_data >$WORKDIR/data.txt
gen_iptables >$WORKDIR/boot_iptables.sh
gen_ifconfig >$WORKDIR/boot_ifconfig.sh
chmod +x ${WORKDIR}/boot_*.sh /etc/rc.local

gen_3proxy >/usr/local/etc/3proxy/3proxy.cfg

cat >>/etc/rc.local <<EOF
bash ${WORKDIR}/boot_iptables.sh
bash ${WORKDIR}/boot_ifconfig.sh
ulimit -n 10048
service 3proxy start
EOF

bash /etc/rc.local

gen_proxy_file_for_user

upload_proxy
#start of timer script

sleep ${timer}; 

pkill -9 -f 3proxy
done

#end of script










